package ClientMachine.ServiceApp;


/**
* ServiceApp/TimeSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Service.idl
* Monday, November 6, 2017 7:44:51 o'clock PM EST
*/

public final class TimeSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public TimeSeqHolder ()
  {
  }

  public TimeSeqHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TimeSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TimeSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TimeSeqHelper.type ();
  }

}
