package ServerMachine.ServiceApp;


/**
* ServiceApp/ServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Service.idl
* Monday, November 6, 2017 7:44:51 o'clock PM EST
*/

public interface ServiceOperations 
{
  String sayHello();
  String bookRoom(String studentID, String campusName, String date, String room_Number, String timeslot);
  String getAvailableTimeSlot(String date);
  boolean cancelBooking(String studentID, String bookingID);
  int createRoom(String date, String room_Number, String[] list_Of_Time_Slots);
  int deleteRoom(String date, String room_Number, String[] list_Of_Time_Slots);
  String changeReservation(String booking_id, String studentID, String campusName, String date, String room_Number, String timeslot);
} // interface ServiceOperations
